name: sandbox
favicon: null
layout_spectrum: 0.23809
typography_spectrum: 0.19943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#515151'
    - '#979797'
    - '#c3c3c3'
    - '#212121'
  brandStrength: 0.5385343653615564
  lightness: 0.6464341059327126
  saturation: 0.04678475158289075
  rhythmicContrast: 0.7753524533472955
purpose: []
