name: sandbox
favicon: null
layout_spectrum: 0.49863
typography_spectrum: 0.19943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#515151'
    - '#979797'
    - '#c3c3c3'
    - '#212121'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
